### ISSUE TITLE
Multiple surfaces in FlexScrollView items sporadically change Z order

### ISSUE THREAD

**Issue by peacechen** [IjzerenHein/famous-flex#45] opened 2015-01-28 03:14 UTC
When the items in a FlexScrollView consist of multiple surfaces, scrolling them in and out of view causes their surfaces' Z order to change seemingly randomly.  I observed this bug in Famo.us's stock Scrollview in their version 0.3.2.  It's been fixed in 0.3.4 so perhaps that may offer some insight into this issue.

This self-contained code recreates it.  The red box should be on top, the blue box just below it, and the red & green bars behind them both.  Scroll all the way down, then all the way up. The red / blue boxes in some of the items drop below the other surfaces.

    define(function(require, exports, module) {
        var Engine             = require('famous/core/Engine');
        var AppView            = require('views/AppView');
        var Surface            = require('famous/core/Surface');
        var ImageSurface       = require('famous/surfaces/ImageSurface');
        var StateModifier      = require('famous/modifiers/StateModifier');
        var RenderNode         = require('famous/core/RenderNode');
        var Transform          = require('famous/core/Transform');
        var FlexScrollView     = require('famous-flex/FlexScrollView');
        
        var mainContext = Engine.createContext();
        mainContext.setPerspective(1000);
        mainContext.setSize([300, 500]);

        this.scrollview = new FlexScrollView({
            // paginated: true,
            // mouseMove: true,
            layoutOptions: {
                //margins: [10, 5, 0, 15], 
                spacing: 2
            }
        });
        mainContext.add(this.scrollview);

        this.items = [];
        this.scrollview.sequenceFrom(this.items);
        this.size = [mainContext.getSize()[0], 200]

        for (var i=0; i<6; i++) {
            var itemModifier = new StateModifier({ size: this.size});
            var itemNode = new RenderNode(itemModifier);

            var background = new ImageSurface({
                size: this.size,
                properties: {
                    backgroundColor: 'grey'
                },
                content: "https://famo.us/blog/wp-content/uploads/2014/12/19b.jpg"
            });
            background.pipe(this.scrollview);
            itemNode.add(background);

            var surface1 = new Surface({
                size: [this.size[0], 20],
                properties: {
                    backgroundColor: 'yellow'
                }
            });
            surface1.pipe(this.scrollview);
            itemNode.add(surface1);

            var surface2 = new Surface({
                size: [this.size[0], 40],
                properties: {
                    backgroundColor: 'green'
                }
            });
            surface2.state = new StateModifier({
                origin: [0, 1],
                align: [0, 1]
            });
            surface2.pipe(this.scrollview);
            itemNode.add(surface2.state).add(surface2);

            var surface3 = new Surface({
                size: [this.size[0]*0.5, this.size[1]*0.75],
                properties: {
                    backgroundColor: 'blue'
                }
            });
            surface3.state = new StateModifier({
                origin: [0.5, 0],
                align: [0.5, 0.2]
            });
            surface3.pipe(this.scrollview);
            itemNode.add(surface3.state).add(surface3);

            var surface4 = new Surface({
                size: [this.size[0]*0.3, this.size[1]*0.3],
                properties: {
                    backgroundColor: 'red'
                }
            });
            surface4.state = new StateModifier({
                origin: [0.5, 0],
                align: [0.5, 0.04]
            });
            surface4.pipe(this.scrollview);
            itemNode.add(surface4.state).add(surface4);

            this.items.push(itemNode);
        }

    });

**Comment by IjzerenHein** [comment] 2015-01-28 09:04
Hi Peace,

This happens because famo.us does not guarentee the order of the nodes in the DOM. Please have a look at this link: http://famo.us/guides/pitfalls

This is not specific to the scrollVIew but basically to any View that dynamically adds surfaces to the render-tree, also RenderController.

The way to address this, is to translate surfaces behind/infront each other and not depend on the DOM ordering, like this:

```javascript
var surface1 = new Surface({
    size: [this.size[0], 20],
    properties: {
        backgroundColor: 'yellow'
    }
});
surface1.pipe(this.scrollview);

itemNode = itemNode.add(new Modifier({
    transform: Transform.inFront
}));
itemNode.add(surface1);

var surface2 = new Surface({...});
surface2.pipe(this.scrollview);
itemNode = itemNode.add(new Modifier({
    transform: Transform.inFront
}));
itemNode.add(surface2);

...
```

**Comment by peacechen** [comment] 2015-01-28 14:52
I had tried applying Transform.inFront to work around the issue in both Famo.us's Scrollview and your FlexScrollView. While it does keep the red & blue boxes on top of the yellow & green bars, they (red/blue) switch order randomly after scrolling.

The initial position of the surfaces is correct.  The issue can be seen when the FlexScrollView is scrolled all the way down then all the way back up.  The items that move out of view and back into view have the surface orders rearranged.  Somehow they fixed this in Famo.us 0.3.4, perhaps by "remembering" the order the surfaces were originally added via a stack?

**Comment by IjzerenHein** [comment] 2015-01-28 15:18
I'm not aware of anything that has changed in famo.us concerning the ordering of DOM-nodes. It is certainly not mentioned in the famo.us release notes:

```markdown
## 0.3.4

### Bug Fixes

- Famous/inputs
    - 0.3.3 did not fix changes to inputs.  All changes from 0.3.2 and 0.3.3 involving inputs have been reverted

## 0.3.3

### Bug Fixes

- Famous/inputs
    - bug in TouchSync where NaN's were produced

## 0.3.2

### Bug Fixes

- Famous/core
    - Fixed issue where Famo.us would break when it took more than a single frame for the browser to load the body

- Famous/inputs
    - Made sync velocities average out to stop wild spikes
    - Fixed logic for GenericSync to always run through the syncs to register even if it hits one that wa slaready registered

- Famous/views
    - Fixed bug where SequentialLayout would not work if you gave children undefined size
```

Could you share your code concerning the red/blue surfaces switching randomly?
I'm pretty sure they are at the same z-translation and therefore the one appears randomly in front of the other when scrolling.

**Comment by peacechen** [comment] 2015-01-28 15:33
Yes the red & blue boxes are both at Transform.inFront.  I'll experiment with offsetting them slightly. It just feels hackish.

        var surface3 = new Surface({
            size: [this.size[0]*0.5, this.size[1]*0.75],
            properties: {
                backgroundColor: 'blue'
            }
        });
        surface3.state = new StateModifier({
            origin: [0.5, 0],
            align: [0.5, 0.2],
            transform: Transform.inFront
        });
        surface3.pipe(this.scrollview);
        itemNode.add(surface3.state).add(surface3);

        var surface4 = new Surface({
            size: [this.size[0]*0.3, this.size[1]*0.3],
            properties: {
                backgroundColor: 'red'
            }
        });
        surface4.state = new StateModifier({
            origin: [0.5, 0],
            align: [0.5, 0.04],
            transform: Transform.inFront
        });
        surface4.pipe(this.scrollview);
        itemNode.add(surface4.state).add(surface4);

I tried to create a fiddle but haven't found a public URL for the famous-flex library.  That code can be dropped into any Famo.us skeleton along with the famous-flex js.

The Famo.us changelog must not be very complete or detailed. There's definitely change in behavior with Z ordering, particularly noticeable with ScrollView.

**Comment by peacechen** [comment] 2015-01-28 15:36
BTW from the pitfalls page:
"The order in which Surfaces are instantiated matters, in regards to browser representation. Since Famo.us creates the DOM elements in the order that your Javascript runs, the default behavior is similar to how the browser parses standard HTML. Surfaces that are instantiated first render behind newer Surfaces because their associated DOM element is created first."

I made sure to instantiate the surfaces in the order that I want them layered.  Reverse-order, as the first instantiated surface is at the bottom, and the later instantiated ones successively on top.  Again this renders properly on first draw. It messes up when the items move in and out of view on the FlexScrollView.

**Comment by IjzerenHein** [comment] 2015-01-28 17:35
Hi Peace,
I don't have the time right now, so I have to get back to you later.
But I was wondering, could you try adding a lot more surfaces to the stock famo.us scrollview? My guess is that when you have sufficient surfaces that the scrollview will start to remove and add surfaces from the DOM (when you scroll), and it will still trigger the problematic situation.

**Comment by peacechen** [comment] 2015-01-29 03:58
I added 6 more surfaces to each item in the stock ScrollView (total of 11 surfaces, over twice as many).   Famo.us 0.3.4 maintains the order properly when the list is scrolled and the items leave and re-enter the view.

**Comment by IjzerenHein** [comment] 2015-01-29 04:00
Can you add many more, like a 100 surfaces?

**Comment by peacechen** [comment] 2015-01-29 04:19
I used a loop to add 100 surfaces, incrementally offsetting the align/origin slightly so I could see all of them. The native ScrollView manages to keep the order properly when scrolling all around.

Not surprisingly, the performance slowed a bit on the native ScrollView. It slowed a lot with the FlexScrollView.  Rough guesstimate 20 fps vs 5 fps.

I tried to work around this issue in FlexScrollView by using Transform.translate with small increments of Z.  This manages to work for the scrolling. However when the FlexScrollView is moved in 3D space (translate and transform), surfaces randomly disappear.

**Comment by IjzerenHein** [comment] 2015-01-29 04:24
Right, that is weird. Can I view the demo online somewhere so I can see the code you are using and debug it?

**Comment by peacechen** [comment] 2015-01-29 05:45
(sent Hein a private demo using FlexScrollView without explicit surface Z ordering, with Z ordering, and another with the stock ScrollView containing 100 list items).

The stock Famo.us ScrollView with just 20 list items will also fail to render surfaces when items are scrolled in and out of view.

**Comment by IjzerenHein** [comment] 2015-01-29 10:37
Conversation was continued through email.

> Peace wrote

Hein,

I can't release the source for the real app, but here's a private link to the live demo:
- *links have been removed*

Currently it's not explicitly setting the Z order. This causes the surfaces to sporadically disappear with scrolling.

With the work-around to explicitly set Z order, the scrolling is fixed but the transform/translate of the FlexScrollView causes surfaces to randomly disappear. The hamburger icon will do the transform/translate.

Let me know if you want me to set the Z order, and if you want additional surfaces added.

Regards,
Peace

**Comment by IjzerenHein** [comment] 2015-01-29 10:37
> Hein wrote

Ok thanks.
Can you also share a version using the Stock famo.us ScrollView (using 100 ListingView items) and an other version which uses the z-translations on different URL's so I can compare those?

**Comment by IjzerenHein** [comment] 2015-01-29 10:37
> Peace wrote

Ok here they are --

FlexScrollView, no Z order adjustments:
links have been removed

FlexScrollView with Z order adjustments:
links have been removed

Stock ScrollView 100+ surfaces:
links have been removed

Note that the middle box ("Specials tonight") has a red border. With 100 of them stacked up and offset, it may look like a solid red box to the left. Zoom in and you'll see the individual borders.

**Comment by IjzerenHein** [comment] 2015-01-29 10:37
> Hein wrote

Hi Peace,
Awesome!

Regarding the 100+ surfaces demo. What I meant was, can you add 100+ list-items to the scrollview? Not more surfaces to a single list-view item. 
What I'm trying to show/debug is that the stock famo.us scrollView will also show the DOM ordering issues once you give it more list-items to work with. This is because it has a different threshold for when it starts adding/removing items from the DOM, but once it starts doing so, it will show the same issues as you see with the FlexScrollView.

**Comment by IjzerenHein** [comment] 2015-01-29 10:38
> Hein wrote

Oh, and can we please continue this conversation on github. Just remove the links and mention that you send me the links. It is important that this information is on github so that other people can view the discussion and learn from it, or I can refer to the discussion directly when a similar question comes up.

**Comment by IjzerenHein** [comment] 2015-01-29 10:38
> Peace wrote

I updated the wwwScrollView demo as you suggested (100 list items instead of 100 surfaces per item lol). You're right the stock ScrollView does eventually miss rendering surfaces.

I'll reply further on the GH thread.

**Comment by IjzerenHein** [comment] 2015-01-29 10:38
> Hein wrote

Yes that's what I thought would happen. The FlexScrollView has a different threshold setting for when items are added/removed from the DOM, it will typically remove all elements from the DOM that are not in the view. I have found that this performs the best on all devices. The stock famo.us scrollview will keep always keep about 10+ list-items in the DOM.
You can also instruct the FlexScrollView to always keep all list-items in the DOM, which can be beneficial to performance when you render only a limited set of list-items. To do this, use:

```javascript
var scrollView = new FlexScrollView({
  layoutAll: true
});
```

**Comment by IjzerenHein** [comment] 2015-01-29 10:39
> Peace wrote

The layoutAll option works like a charm! You might want to add that comment to the thread for other people's benefit too.

Is it bad to compose items with multiple surfaces? I first tried a single surface containing markup to place the child elements, but it was such a hack merging a string of markup with variables inserted. Famo.us really could benefit from something like React's JSX.

**Comment by IjzerenHein** [comment] 2015-01-29 10:39
No I don't want to give the recommendation to use that option.

The real cause of the problem is that you cannot control the order of the items in the DOM using famo.us (if you think this is a bug, then please report it to famo.us). What you need to do is fix your code and add z-translations to those surfaces that you want to be displayed in front. As your app evolves you will very likely get multiple views and you will start using a RenderController to show/hide the views. When you do that, it is very likely that you will get into the same mess and the ordering is different after using 'renderController.show', so using layoutAll wont help you there.
Have you taken the famo.us University? I think it should mention this behavior more clearly as lots of people who start using famo.us run into it (I know I did back then).

**Comment by IjzerenHein** [comment] 2015-01-29 10:39
Oh as for your second question.

No, it's no problem to compose items with multiple surfaces, in many cases you will have to do this, and it is the only way to handle different click events on single list-item.
In those cases where I don't need to handle separate click events for the list-item, I often do create a single surface and pass the child-divs as content to the surface. I used to concat those strings in JS but it gets real messy as you may have noticed.
I now mostly use handlebars templates for that. Please have a look at the famous-flex-chat sourcecode, it uses handlebars to compile an HTML template and set the content for a surface:
https://github.com/IjzerenHein/famous-flex-chat

**Comment by IjzerenHein** [comment] 2015-01-30 08:14
Hi, please close this issue if you feel it was answered satisfactory.

**Closed** 2015-02-02 03:19 UTC
Labels: question
