### ISSUE TITLE
Famo.us still alive

### ISSUE THREAD

**Issue by svdoever** [IjzerenHein/famous-flex#92] opened 2015-04-25 21:02 UTC
Hi IjzerenHein,

Not an issue with your code, but a question about famo.us...

What is you opinion about the Famo.us framework? Is it still alive? The repository at https://github.com/Famous/famous is not updated very frequently, their latest blog post is of Januari 2015... 

I know you invested a lot on their framework, wondering what your opinion is.

Groeten,
Serge van den Oever

**Comment by ArEnSc** [comment] 2015-04-25 21:20
I believe they are still around they are working on a we go based rendering engine after deprecating the css3 based one. The issue is that they don't understand developers want a view and a controller layer, and widgets which hopefully ijzrenhien can continue to work on :P

**Comment by bardu** [comment] 2015-04-26 02:46
I asked the same question in March directly to Steve Newcomb, CEO of famous, and this was his response:

"We've had a demo day every Thursday and have never stopped.  If you follow our Twitter feed, we are posting there.  In terms of the newsletter, we've made a change in our approach. Largely, I felt as though the newsletter was too "marketing" speak and I have made a personnel switch so that now engineers are writing the newsletter.  We are stronger than ever, just getting ready for the next big push which is coming in April - new version of Famo.us with WebGL support, new physics engine and an announcement of Famo.us front end containers connected to our backed Hub.  In terms of the blog, we've stopped posting to it because we are building a new website to replace the old one.  The new one goes up April 2."

Now we have end of April and nothing happens. I have a bad gut feeling!

**Comment by IjzerenHein** [comment] 2015-04-27 08:33
Hello Serge,

That's a very good question. I know for a fact that the guys at famo.us are working very hard at the new v1.0 release (also known as Mixed-mode). I think this is also the reason that their blog has gone a bit silent. And since the v0.3.x version, they are only releasing critical patches to v0.3, so don't expect any big things there.
My best bet is that the new 1.0 version will be released this summer (I've heard rumours of some delays) and the API will be quite different and more user friendly.
Personally, I think it's gonna be a sweet year for famo.us and I can't wait for v1.0. I just wish they were a bit more transparent with their development process and deadlines.

cheers,
Hein

**Comment by talves** [comment] 2015-04-28 01:02
:+1: They are also changing to [MIT Licensing on the MixedMode version too][1].
> I can't wait for v1.0. I just wish they were a bit more transparent with their development process and deadlines.

[1]: https://www.youtube.com/watch?v=Ujp5Qc2gstI&feature=youtu.be&t=13m18s

**Comment by IjzerenHein** [comment] 2015-04-28 01:38
Awesome, thanks for sharing that Tony!

**Comment by ShawnOceanHu** [comment] 2015-04-28 01:46
+1 can't wait for v1.0 :+1:

**Comment by talves** [comment] 2015-04-28 06:32
No problem Hein. :smile: 

@ShawnOceanHu not sure it will be called v1.0.  As Steve said in the video, they are not sure yet either.  I am with @IjzerenHein on this one.  I wish they were a little more transparent.  MIT should be Open source development also.  The future will give us answers.  Let's hope it is the answers we are looking for.

**Comment by The1nternet** [comment] 2015-05-19 19:57
So what is famous-flex gonna do when v1.0 comes out and is not backwards compatible whatsoever with v0.3?

**Comment by svdoever** [comment] 2015-05-19 20:06
I think ijzerenHein has some work to do:-) There is a developer preview at May 21, see https://www.eventbrite.com/e/famous-developer-preview-tickets-16824564726?ref=estw. Someone in the neighborhood to join and report? IjzerenHein, did you join the Demo Day in Amsterdam? See http://www.meetup.com/Famo-us-Amsterdam/events/222230050. I didn't see it, otherwise I would have gone, I live in Amsterdam!@#$% Any news from Amsterdam? At PhoneGapDay Europe 2015 (yesterday in Amsterdam) there was a nice presentation about Html GL (https://github.com/PixelsCommander/HTML-GL).

**Comment by IjzerenHein** [comment] 2015-05-19 20:30
After the new API has been made public, I will re-evaluate which parts of famous-flex (and the other libs) are still needed and useful. This may take some time, as I want to get some real experience with the new API before making any decisions.

**Comment by IjzerenHein** [comment] 2015-05-19 20:40
@svdoever I did visit the demo day and did a talk on the AnimationController and the new supported map-providers in https://github.com/IjzerenHein/famous-map. Unfortunately no video recordings were made, so you can't view it on youtube. 
I was at the phonegap event in Amsterdam yesterday as well. Were you there serge? The HTML-GL tech was very interesting (I had already seen the demos online). I was actually sitting next to Denis when he was preparing that talk :) It could be very interesting if the DOM rasterisation step can be improved (it is apparently still quite slow and not suited when the DOM updates constantly).

**Comment by svdoever** [comment] 2015-05-19 20:47
Haha, I have been talking to Denis for at least half an hour after his talk. Showed him our work done with Famo.us, and told him about our frustrations with Famo.us in both the long period of silence, and the difficulty to get things really working. He is working at UPC, hundred meters from my office Macaw at Schiphol-Rijk, so we will meet soon for coffee.

It would be great if the DOM rasterization becomes fast indeed. I hoped Famo.us would be good enough with the transformation of complete divs containing complete html elements, but it turned out to be really dissapointing, especially the pixelation of fonts when zooming in. Did you see new stuff regarding the mixed mode?

**Comment by talves** [comment] 2015-05-19 20:49
@IjzerenHein are you on https://famous-community.slack.com ?

**Comment by svdoever** [comment] 2015-05-19 20:54
No, could you add me? Email: svdoever@gmail.com

**Comment by talves** [comment] 2015-05-19 20:57
Go to the link and sign-up.

-Tony

**Comment by svdoever** [comment] 2015-05-19 21:01
Ah sorry Tony, message wasn’t for me:) I tried to sign in but it is invitation only….

**Comment by talves** [comment] 2015-05-19 21:04
@svdoever try this link http://slack.famous.org
It should be an invitation link.

**Comment by svdoever** [comment] 2015-05-19 21:11
Thanks! I joined!

**Comment by svdoever** [comment] 2015-05-19 21:26
New information here.... http://staging.famous.org/

**Closed** 2015-07-21 19:37 UTC
Labels: question
