### ISSUE TITLE
Surfaces inside of scroll view are not updating their height

### ISSUE THREAD

**Issue by drewdhutchins** [IjzerenHein/famous-flex#69] opened 2015-02-16 19:13 UTC
I have built an application that uses a scroll view to display a list of surfaces.  Some of the surfaces just have text but others have images.  For my surfaces that have images, it appears as though the surface size is being set before the image has fully loaded and is therefore not tall enough to contain the image.  If the surface is not at the end of the list, I can scroll around some and the surface will adjust itself.  However, if the surface is at the end of the list, the image over hangs the entire scroller and therefore I can't scroll around to get it to resize the surface.  I threw together a quick hack that adds an onload function to each image, and then resets the content of the surface once the image has finished loading.  This method sort of works, but its not ideal.  I was just wondering if you had any ideas of a better way to solve this issue.

**Comment by motiazu** [comment] 2015-02-17 16:47
Try setting alwaysLayout to true in your options. Example:

```
 boxesLayout = new FlexScrollView({
            ...
            alwaysLayout: true,
            ...
        });
```

**Comment by drewdhutchins** [comment] 2015-02-17 17:13
Thank you for your help.  This is really close to fixing my issue.  The only remaining problem is this.  If the surface is currently visible while the image is loading, the surface does not resize itself until it is scrolled out of view and then back in to view. So for my issue I mentioned above where if the image is the last item in the scroller, I could never get it to resize because it was hanging past the entire scroller, I can now get that to resize, but only by scrolling the other way until it is completely out of view.  Any thoughts on this?

**Comment by IjzerenHein** [comment] 2015-02-17 18:23
Thanks @motiazu!
@drewdhutchins I am almost inclined to say that this is a bug in famo.us itself. Famo.us caches the size of a renderable when true-size is specified, so it doesn't have to "ping" the DOM all the time. Could you share a live demo so I can have look and investigate the problem?

**Comment by IjzerenHein** [comment] 2015-02-17 21:13
I've investigated the issue with the links you send me, and as I feared the problem is in the famo.us Surface itsself. This is a fragment of the 'Surface.commit' function:

```javascript
Surface.prototype.commit = function commit(context) {
   ...
        if (this.size) {
            var origSize = context.size;
            size = [this.size[0], this.size[1]];
            if (size[0] === undefined) size[0] = origSize[0];
            if (size[1] === undefined) size[1] = origSize[1];
            if (size[0] === true || size[1] === true) {
                if (size[0] === true){
                    if (this._trueSizeCheck || (this._size[0] === 0)) {
                        var width = target.offsetWidth;
                        if (this._size && this._size[0] !== width) {
                            this._size[0] = width;
                            this._sizeDirty = true;
                        }
                        size[0] = width;
                    } else {
                        if (this._size) size[0] = this._size[0];
                    }
                }
```

The problem is with the line `if (this._trueSizeCheck || (this._size[0] === 0)) {` which causes famo.us to only obtain the width/height once. The variable `_trueSizeCheck` is reset only when the content of the surface is changed, or its size is changed. But for surfaces containing delayed loaded images this causes  problems.
I've already added various workarounds to the FlexScrollView to deal with this problem, and I explicitely set the _trueSizeCheck on surfaces to force famo.us to re-query the DOM. Currently the only thing I can imagine to solve this, is to add an additional option to the FlexScrollView, which forces famo.us to query the DOM on true-size renderables on every render-cycle. That should solve your problem. But it would be better if this is solved intrinsicly and elegantly in famo.us itsself.

**Comment by motiazu** [comment] 2015-02-17 21:22
Will it possible as a local workaround to change _trueSizeCheck when some imageloaded event fires? That could do the trick and it shouldn't be heavy performance wise since this will be done only once per imagesurface.

**Comment by IjzerenHein** [comment] 2015-02-17 21:24
Yes that would work for ImageSurface. I think @drewdhutchins uses a more complex DOM structure, where the image is inside other div's, so I'm not sure how you could attach an event handler to that.

**Comment by motiazu** [comment] 2015-02-17 21:35
http://stackoverflow.com/questions/10121797/javascript-image-onload-event-binding
With this you can listen to image load event. Just loop through the images and keep a mapping to their surfaces to update _trueSizeCheck .

**Comment by drewdhutchins** [comment] 2015-02-17 21:53
Thank you for all the help @IjzerenHein and @motiazu.  I have decided that for now, I am going to go back to my original hack of  adding an onload function to each image, but instead of resetting the content of the surface, I am setting _trueSizeCheck to true like @motiazu suggested.  In my testing thus far, this appears to work pretty well and will suit my needs for now.

**Comment by IjzerenHein** [comment] 2015-02-17 22:11
Awesome!

Please close this issue if you feel it was answered satisfactory. Also, if you like this lib, please show your support by giving it a star.

cheers, Hein

**Closed** 2015-02-17 22:45 UTC
Labels: question, wontfix
